version: '3'

services:
  worker:
    image: ta-worker:latest
    pull_policy: if_not_present
    ports:
      - "50054:50054"
    depends_on:
      - main

  main:
    build: .
    ports:
      - "50052:50052"
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
