"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Ping(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    RETURN_TO_PORT_FIELD_NUMBER: builtins.int
    return_to_port: builtins.int

    def __init__(self, *, return_to_port: builtins.int=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['return_to_port', b'return_to_port']) -> None:
        ...
global___Ping = Ping

@typing.final
class Pong(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(self) -> None:
        ...
global___Pong = Pong