"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
from . import types_pb2
import typing
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Task(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    BASE_TASK_FIELD_NUMBER: builtins.int
    ACCOUNT_ID_FIELD_NUMBER: builtins.int

    @property
    def base_task(self) -> types_pb2.BaseTask:
        ...

    @property
    def account_id(self) -> types_pb2.UUID:
        ...

    def __init__(self, *, base_task: types_pb2.BaseTask | None=..., account_id: types_pb2.UUID | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['account_id', b'account_id', 'base_task', b'base_task']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['account_id', b'account_id', 'base_task', b'base_task']) -> None:
        ...
global___Task = Task

@typing.final
class Response(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    STATUS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    status: types_pb2.Status.ValueType
    message: builtins.str

    def __init__(self, *, status: types_pb2.Status.ValueType=..., message: builtins.str | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['_message', b'_message', 'message', b'message']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['_message', b'_message', 'message', b'message', 'status', b'status']) -> None:
        ...

    def WhichOneof(self, oneof_group: typing.Literal['_message', b'_message']) -> typing.Literal['message'] | None:
        ...
global___Response = Response